- name: Install nginx web server & php-fpm
  apt:
    state: latest
    pkg:
      - nginx
      - php-fpm
      - composer
      - php7.3-pgsql
      - php7.3-sqlite3
      - php-xml
      - php-intl

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure Nginx
  template:
    src: templates/symfony.conf.j2
    dest: /etc/nginx/sites-enabled/symfony.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nginx
